Update staging.yml

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -27,15 +27,15 @@ jobs:
         shell: bash
 
       - name: Build docker containers & run tests
-        run: npm run test:start
+        run: npm run test:run
 
-      - name: Cleanup
-        if: success()
-        run: npm run test:stop
-          # # if [ "${{ steps.test.outcome }}" == 'success' ]; then
-          #   echo "Tests passed!"
+      # - name: Cleanup
+      #   if: success()
+      #   run: npm run test:stop
+      #     # # if [ "${{ steps.test.outcome }}" == 'success' ]; then
+      #     #   echo "Tests passed!"
             
-          # else
-          #   echo "Tests failed."
-          #   exit 1
-          # fi
+      #     # else
+      #     #   echo "Tests failed."
+      #     #   exit 1
+      #     # fi
